# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f58f3c1bbc459afa607912104082b9e10a91083e13e7276625b4653fda3fe1abce382f703faa3044c59de4328ef59c20bf1edeb42e3f13c846cae1dec5b2fdd

test:
  secret_key_base: c131b72e4117143173d5e9505d7f27658205ee3135d26376af3e464cb3b722341af7125ae5da527902e565eea19b0db4125968a26ce64a86467dcd997ec976d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
